### PR TITLE
Extract date parsing service

### LINKED ISSUE #159: Date parsing: Changing the top level limit to not be 2 + current year
Running the Redivis ETL Job resulted in this error:
```

app/services/solr_mapper.rb:112:in 'block in SolrMapper#temporal_field': Unable to parse range from '1912-02-13/2077-12-28': undefined method '>' for nil (ParseDate::Error)
...
/Users/hudakhan/.rvm/gems/ruby-3.4.2/bundler/gems/parse_date-a0bf56fc9651/lib/parse_date.rb:46:in 'ParseDate.year_range_valid?': undefined method '>' for nil (NoMethodError)

    return false if first_year > upper_bound || last_year > upper_bound
```
The reason appears to be that the default upper year limit for the parse range gem is the current year + 2, and the upper range for this date range is 2077.

### LINKED ISSUE #163: Investigate if the edtf gem will handle our date parsing requirements for both mapping from source metadata and solr mapping
Although we are using ParseDate to handle date parsing for both mapping from provider metadata to a DataWorks schema, we would like to check if the EDTF parsing gem may be able to help us with our date parsing requirements

### PR DESCRIPTION
**Pull request by aaron-collier**
This switches from ParseDate to Edtf for ambiguous date parsing and returning a range array.

Fixes #159 
Fixes #163

### CODE REVIEW

File: app/services/date_parsing.rb [hunk 1]
```diff
@@ -0,0 +1,19 @@
+# frozen_string_literal: true
+
+# Date parsing service to extract date ranges and other formats.
+class DateParsing
+  # Regex for a date range pattern with a slash: 2023-01-02T19:20:30+01:00/2025-01-01
+  DATESTR_REGEX = %r/\b(\d{4})\b.*?\/.*?\b(\d{4})\b/im
+
+  # Parses a date range string and returns an array array of all years in the range
```
Comment (justinlittman) [inline app/services/date_parsing.rb:8]: Typo

File: app/services/date_parsing.rb [hunk 2]
```diff
@@ -0,0 +1,19 @@
...
+  #
+  # @param date_range_string [String] The date range string to parse.
+  # @return [Array<int>, nil] The range from parsed start to end dates or nil if invalid.
+  def self.parse_date_range(date_range_string)
+    return nil if date_range_string.blank?
+    return nil unless date_range_string.match(DATESTR_REGEX)
+
+    # Extract the start and end dates from the matched pattern
+    (Date.edtf(Regexp.last_match(1)).year..Date.edtf(Regexp.last_match(2)).year).to_a
```
Comment (justinlittman) [inline app/services/date_parsing.rb:17]: What is "Date.edtf" buying here? It seems like the regex is already matching a year.

Comment (aaron-collier) [reply app/services/date_parsing.rb:17]: Good point. This was basically removing a call to parsing the date, I will simplify.

**Review by justinlittman — APPROVED** [review]
